import{a as w,S as P,i as s}from"./assets/vendor-CZ1QA36h.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const q="57655866-60005b456cabde49bcceaed9d";async function u(a,o){try{return(await w.get("https://pixabay.com/api/",{params:{key:q,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}catch(t){throw console.log("Sorry, there has been an error"),t}}const v=new P(".gallery a",{captionDelay:250}),m=document.querySelector(".gallery"),f=document.querySelector(".loader"),g=document.querySelector(".load-btn");function h(a){const o=a.map(({webformatURL:t,largeImageURL:c,tags:e,likes:r,views:i,comments:L,downloads:S})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${c}">
            <img class="gallery-image" src="${t}" alt="${e}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes</b><br>${r}</p>
            <p class="info-item"><b>Views</b><br>${i}</p>
            <p class="info-item"><b>Comments</b><br>${L}</p>
            <p class="info-item"><b>Downloads</b><br>${S}</p>
          </div>
        </li>
      `).join("");m.insertAdjacentHTML("beforeend",o),v.refresh()}function E(){m.innerHTML=""}function M(){f.classList.remove("hidden")}function $(){f.classList.add("hidden")}function l(){g.classList.remove("hidden")}function y(){g.classList.add("hidden")}const H=document.querySelector(".form");document.querySelector(".form-input");document.querySelector("#data-list");const R=document.querySelector(".load-btn");let n=1,p="",d=0;const b=15;H.addEventListener("submit",O);async function O(a){a.preventDefault();const o=a.target.elements["search-text"].value.trim();if(!o){s.error({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}p=o,E(),y(),M();try{const t=await u(o,n=1);if(d=t.totalHits,t.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(t.hits),n*b<d&&l()}catch{s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{$(),a.target.reset()}}R.addEventListener("click",B);async function B(){n++;try{const a=await u(p,n);h(a.hits);const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,left:0,behavior:"smooth"}),n*b>=d?(y(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):l()}catch{s.error({title:"Error",message:"Failed to fetch more images. Please try again.",position:"topRight"}),l()}}
//# sourceMappingURL=index.js.map
