import{a as q,S as v,i as s}from"./assets/vendor-CZ1QA36h.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const E="57655866-60005b456cabde49bcceaed9d";async function m(a,o){try{return(await q.get("https://pixabay.com/api/",{params:{key:E,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}catch(t){throw console.log("Sorry, there has been an error"),t}}const M=new v(".gallery a",{captionDelay:250}),f=document.querySelector(".gallery"),h=document.querySelector(".loader"),g=document.querySelector(".load-btn");function y(a){const o=a.map(({webformatURL:t,largeImageURL:c,tags:e,likes:r,views:i,comments:w,downloads:P})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${c}">
            <img class="gallery-image" src="${t}" alt="${e}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes</b><br>${r}</p>
            <p class="info-item"><b>Views</b><br>${i}</p>
            <p class="info-item"><b>Comments</b><br>${w}</p>
            <p class="info-item"><b>Downloads</b><br>${P}</p>
          </div>
        </li>
      `).join("");f.insertAdjacentHTML("beforeend",o),M.refresh()}function R(){f.innerHTML=""}function p(){h.classList.remove("hidden")}function b(){h.classList.add("hidden")}function d(){g.classList.remove("hidden")}function l(){g.classList.add("hidden")}const $=document.querySelector(".form");document.querySelector(".form-input");document.querySelector("#data-list");const H=document.querySelector(".load-btn");let n=1,L="",u=0;const S=15;$.addEventListener("submit",O);async function O(a){a.preventDefault();const o=a.target.elements["search-text"].value.trim();if(!o){s.error({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}L=o,R(),l(),p();try{const t=await m(o,n=1);if(u=t.totalHits,t.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(t.hits),n*S<u?d():(l(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b(),a.target.reset()}}H.addEventListener("click",B);async function B(){n++,l(),p();try{const a=await m(L,n);y(a.hits);const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,left:0,behavior:"smooth"}),n*S>=u?(l(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):d()}catch{s.error({title:"Error",message:"Failed to fetch more images. Please try again.",position:"topRight"}),d()}finally{b()}}
//# sourceMappingURL=index.js.map
